name: sar-intro
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - 'python=3.8'
  - 'notebook=6.2.0'
  - 'jupyterhub=1.3.0'
  - 'jupyterlab=2.2.9'
  - "cudatoolkit=11.2" 
  -  'beautifulsoup4=4.9.*'
  - 'conda-forge::blas=*=openblas'
  - 'bokeh=2.2.*'
  - 'bottleneck=1.3.*'
  - 'cloudpickle=1.6.*'
  - 'cython=0.29.*'
  - 'dask=2020.12.*'
  - 'dill=0.3.*'
  - 'h5py=3.1.*'
  - 'ipywidgets=7.6.*'
  - 'ipympl=0.5.*'
  - 'matplotlib-base=3.3.*'
  - 'numba=0.52.*'
  - 'numexpr=2.7.*'
  - 'pandas=1.1.*'
  - 'patsy=0.5.*'
  - 'protobuf=3.14.*'
  - 'pytables=3.6.*'
  - 'scikit-image=0.18.*'
  - 'scikit-learn=0.24.*'
  - 'scipy=1.5.*'
  - 'seaborn=0.11.*'
  - 'sqlalchemy=1.3.*'
  - 'statsmodels=0.12.*'
  - 'sympy=1.7.*'
  - 'vincent=0.4.*'
  - 'widgetsnbextension=3.5.*'
  - 'xlrd=1.2.*'
  - gdal 
  - # cmake pdal python-pdal entwine
  - geopandas 
  - rasterio 
  - xarray 
  - rioxarray 
  - pyproj 
  - cartopy 
  - ipyleaflet 
  - h5netcdf 
  - netcdf4
