name: sar-intro
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - libcurl
  - pycparser
  - pycosat
  - py-lief
  - reproc
  - icu
  - libmambapy
  - conda-package-handling
  - jinja2
  - libxml2
  - liblief
  - libffi
  - charset-normalizer
  - ruamel_yaml
  - ld_impl_linux-64
  - beautifulsoup4
  - six
  - libuuid
  - tzdata
  - brotlipy
  - pybind11-abi
  - libgomp
  - python-libarchive-c
  - c-ares
  - wheel
  - psutil
  - sqlite
  - libev
  - markupsafe
  - libarchive
  - setuptools
  - yaml
  - cffi
  - xz
  - chardet
  - libgcc-ng
  - readline
  - libssh2
  - ripgrep
  - pysocks
  - zlib
  - libnghttp2
  - colorama
  - filelock
  - lz4-c
  - reproc-cpp
  - zstd
  - pkginfo
  - glob2
  - pyopenssl
  - patchelf
  - python_abi
  - tk
  - libstdcxx-ng
  - ncurses
  - requests
  - libnsl
  - idna
  - soupsieve
  - pytz
  - libiconv
  - yaml-cpp
  - urllib3
  - krb5
  - cryptography
  - bzip2
  - libmamba
  - _libgcc_mutex
  - libsolv
  - _openmp_mutex
  - lzo
  - libzlib
  - libedit
  - keyutils
  - tqdm
  - pyyaml
  - notebook
  - jupyterhub
  - jupyterlab
  - nodejs=16.14
  - altair
  - bokeh
  - bottleneck
  - cloudpickle
  - conda-forge::blas[build=openblas]
  - cython
  - dask
  - dill
  - h5py
  - ipympl
  - ipywidgets
  - matplotlib-base
  - numpy<2
  - numba
  - numexpr
  - pandas
  - patsy
  - protobuf
  - pytables
  - scikit-image
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels
  - sympy
  - widgetsnbextension
  - xlrd
  - cmake
  - pdal
  - python-pdal
  - entwine
  - ipyleaflet
  - gdal
  - pyproj
  - richdem
  - rasterio
  - xarray
  - zarr
  - rioxarray
  - netcdf4
  - h5netcdf
  - astropy
  - pyrosar
  - pygmt
  - geopandas
  - cartopy
  - isce2
  - isce3
  - dask-geopandas
  - eoreader
  - fiona
  - shapely
  - leafmap
  - leafmaptools
  - jupyterlab-git
  - jupyterlab_code_formatter
  - bqplot
  - pandas-profiling
  - panel
  - pythreejs
  - ipycytoscape
  - evidently
  - jupytext
  - voila
  - nikola
  - nbdime
  - ipyparallel
  - nbformat
  - fastai::nbdev
  - nbclient
  - nbqa
  - dask-sql
  - dask-labextension
  - jupyterlab-drawio
  - jupyterlab-system-monitor
  - jupyterlab-lsp
  - jupyter-lsp
  - jupyter-lsp-python
  - jupyter-lsp-r
  - python-lsp-server
  - r-languageserver
  - r-base
  - r-caret
  - r-crayon
  - r-devtools
  - r-e1071
  - r-forecast
  - r-hexbin
  - r-htmltools
  - r-htmlwidgets
  - r-irkernel
  - r-nycflights13
  - r-randomforest
  - r-rcurl
  - r-rmarkdown
  - r-rodbc
  - r-rsqlite
  - r-shiny
  - r-tidyverse
  - rpy2
  - unixodbc
  - r-terra
  - r-rgdal
